"""empty message

Revision ID: b751050b1893
Revises: 76fb62ee1d26
Create Date: 2025-02-19 18:30:53.676251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b751050b1893'
down_revision = '76fb62ee1d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.String(length=25), nullable=False),
    sa.Column('character_name', sa.String(length=25), nullable=False),
    sa.Column('species', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
